export const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publisher: "HarperCollins",
    year: 1960,
    image:
      "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41j-s9fHJcL.jpg",
    price: 9.99,
    category: "read",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    publisher: "Penguin Books",
    year: 1949,
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    price: 8.99,
    category: "current",
  },
  {
    id: 3,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publisher: "Little, Brown and Company",
    year: 1951,
    image:
      "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91HPG31dTwL.jpg",
    price: 10.99,
    category: "want",
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publisher: "Scribner",
    year: 1925,
    image: "https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg",
    price: 7.99,
    category: "read",
  },
  {
    id: 5,
    title: "Brave New World",
    author: "Aldous Huxley",
    publisher: "Harper Perennial Modern Classics",
    year: 1932,
    image:
      "https://pagdandi.org/wp-content/uploads/2021/04/Brave-New-World.jpg",
    price: 12.99,
    category: "current",
  },
  {
    id: 6,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publisher: "Penguin Classics",
    year: 1813,
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL.jpg",
    price: 6.99,
    category: "want",
  },
  {
    id: 7,
    title: "Not To Kill a Mockingbird",
    author: "Brett Lee",
    publisher: "HarperKitabVale",
    year: 1960,
    image:
      "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41j-s9fHJcL.jpg",
    price: 9.99,
    category: "read",
  },
  {
    id: 8,
    title: "2001",
    author: "George Washington",
    publisher: "Duck Books",
    year: 1949,
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    price: 8.99,
    category: "current",
  },
  {
    id: 9,
    title: "The Catcher on the Road",
    author: "J.D. Dutta",
    publisher: "Big, Black and Company",
    year: 1951,
    image:
      "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91HPG31dTwL.jpg",
    price: 10.99,
    category: "want",
  },
  {
    id: 10,
    title: "The Great Ambani",
    author: "Amit Modi",
    publisher: "Reliance",
    year: 1925,
    image: "https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg",
    price: 7.99,
    category: "read",
  },
  {
    id: 11,
    title: "Brave New Rahul",
    author: "Sonie Gandhi",
    publisher: "Not So Classics",
    year: 1932,
    image:
      "https://pagdandi.org/wp-content/uploads/2021/04/Brave-New-World.jpg",
    price: 12.99,
    category: "current",
  },
  {
    id: 12,
    title: "Shame and Honour",
    author: "Jane Doe",
    publisher: "Tiger Classics",
    year: 1813,
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL.jpg",
    price: 6.99,
    category: "want",
  },
  {
    id: 13,
    title: "The Great Ambani: Part Two",
    author: "Amit Modi",
    publisher: "Reliance",
    year: 1925,
    image: "https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg",
    price: 7.99,
    category: "none",
  },
  {
    id: 14,
    title: "Brave New Rahul: Uprising",
    author: "Sonie Gandhi",
    publisher: "Not So Classics",
    year: 1932,
    image:
      "https://pagdandi.org/wp-content/uploads/2021/04/Brave-New-World.jpg",
    price: 12.99,
    category: "none",
  },
  {
    id: 15,
    title: "Shame and Honour: Endgame",
    author: "Jane Doe",
    publisher: "Tiger Classics",
    year: 1813,
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL.jpg",
    price: 6.99,
    category: "none",
  },
];
